swap_platform:
    resource: "@SwapPlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

inscription:
    path: /inscription
    defaults:
        _controller: SwapUserBundle:Security:inscription

login:
    path: /login
    defaults:
        _controller: SwapUserBundle:Security:login

login_check:
    path: /compte

logout:
    path: /logout
