<?php

namespace Swap\PlatformBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
	public function swapRecovery($data) {
		$qb = $this->createQueryBuilder('m');

		$qb
		->where('m.parentId is null')
		->andWhere($qb->expr()->orX(
		$qb->expr()->eq('m.author', $idUser),
		$qb->expr()->eq('m.recipient', $idUser)
		))
		;

		return $qb
		->getQuery()
		->getResult();
	}

	public function serviceRecovery($data) {
		$qb = $this->createQueryBuilder('m');

		$qb
		->andWhere('m.lattitude BETWEEN :lattitude1 AND :lattitude2')
		->setParameter('lattitude1', $data[0])  
		->setParameter('lattitude2', $data[3])
		;

		return $qb;
	
	}
}
