swap_platform_homepage:
    path:     /
    defaults: { _controller: SwapPlatformBundle:Swap:index }

swap_platform_moncompte:
    path:     /compte
    defaults: { _controller: SwapPlatformBundle:Swap:compte }

swap_platform_profil:
    path:     /profil
    defaults: { _controller: SwapPlatformBundle:Swap:profil }

swap_platform_inscription:
    path:     /inscription
    defaults: { _controller: SwapPlatformBundle:Swap:inscription }

swap_platform_modal:
    path:     /modal
    defaults: { _controller: SwapPlatformBundle:Swap:modal }

swap_ajouter_service:
    path:     /ajouter-swap
    defaults: { _controller: SwapPlatformBundle:Service:ajouter }

swap_ajouter_service_details:
    path:     /ajouter-swap-details/{id}
    defaults: { _controller: SwapPlatformBundle:Service:detailsService }

swap_search:
    path:     /rechercher-swap
    defaults: { _controller: SwapPlatformBundle:Service:search }

swap_focus:
    path:     /swap/{id}
    defaults: { _controller: SwapPlatformBundle:Service:swapFocus }

swap_message_send:
    path:     /send-message/{id}/{idUser}
    defaults: { _controller: SwapPlatformBundle:Message:sendMessage }

swap_mail_box:
    path:     /mail-box/
    defaults: { _controller: SwapPlatformBundle:Message:mailBox}

swap_message_conversation:
    path:     /message-conversation/{id}/{recipientId}
    defaults: { _controller: SwapPlatformBundle:Message:conversation}